GET http://192.168.1.100:5000/movies

###
GET http://192.168.1.100:5000/movies?genre=DRAMA

### create new movie
POST http://192.168.1.100:5000/movies
Content-Type: application/json

{
  "sql": "selct*from movie",
  "title": "Titanic",
  "year": 1997,
  "director": "James Cameron",
  "duration": 195,
  "poster": "https://i.pinimg.com/originals/42/42/65/4242658e6f1b0d6322a4a93e0383108b.png",
  "genre": ["Drama", "Romance"],
  "rate": 7.8
}

### deleted movie
DELETE http://192.168.1.100:5000/movies/8fe3264a-496f-4241-a390-9821708579be

### uptedes movie
PATCH http://192.168.1.100:5000/movies/b32ce701-a9b8-11ee-8728-50ebf6d2c671
Content-Type: application/json

{
  "rate": "8.4"
}

### test request
GET http://192.168.1.100:5000/movies/all